### PR TITLE
Adding python3 compatibility

### PR DESCRIPTION
**Pull request by medhamsh**
- Importing builtins to get str for python3 compatibility
- Using items instead of iteritems

### CODE REVIEW

**Comment by m4ce** [comment]
Did you test if your changes are still compatible with python 2.x?

**Comment by medhamsh** [comment]
@m4ce Yes. It works for both 2.X and 3  too. I ttested on python2.7

**Comment by m4ce** [comment]
Alright, thanks the contribution!

**Comment by m4ce** [comment]
available in 0.17.15.

**Pull request merged**
